// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20221118094708_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.ESOEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Obj_gv_type")
                        .HasColumnType("text");

                    b.Property<int?>("Obj_number")
                        .HasColumnType("integer");

                    b.Property<string>("Obt_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("PL_T")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("P_minus")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("P_plus")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ESOEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
